
2025-02-08 11:53:18,027 INFO Logger is configured with simple rotating file handler.
2025-02-08 11:53:18,028 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 11:53:18,029 INFO Starting up TCP server on localhost:60760
2025-02-08 11:53:18,029 INFO Flet app has started...
2025-02-08 11:53:18,029 INFO App URL: tcp://localhost:60760
2025-02-08 11:53:18,034 INFO Starting Flet View app...
2025-02-08 11:53:18,034 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 11:53:18,423 INFO App session started
2025-02-08 11:55:49,864 INFO Logger is configured with simple rotating file handler.
2025-02-08 11:55:49,865 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 11:55:49,866 INFO Starting up TCP server on localhost:60775
2025-02-08 11:55:49,869 INFO Flet app has started...
2025-02-08 11:55:49,869 INFO App URL: tcp://localhost:60775
2025-02-08 11:55:49,869 INFO Starting Flet View app...
2025-02-08 11:55:49,870 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 11:55:50,130 INFO App session started
2025-02-08 11:58:21,261 INFO Logger is configured with simple rotating file handler.
2025-02-08 11:58:21,261 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 11:58:21,266 INFO Starting up TCP server on localhost:60786
2025-02-08 11:58:21,266 INFO Flet app has started...
2025-02-08 11:58:21,266 INFO App URL: tcp://localhost:60786
2025-02-08 11:58:21,266 INFO Starting Flet View app...
2025-02-08 11:58:21,266 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 11:58:21,435 INFO App session started
2025-02-08 11:58:42,286 ERROR Future exception was never retrieved
future: <Future finished exception=NameError("name 'selected_item_id' is not defined")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 225, in on_delete_item
    if selected_item_id:
       ^^^^^^^^^^^^^^^^
NameError: name 'selected_item_id' is not defined. Did you mean: 'register_item_id'?
2025-02-08 12:01:53,898 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:01:53,898 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:01:53,898 INFO Starting up TCP server on localhost:60811
2025-02-08 12:01:53,898 INFO Flet app has started...
2025-02-08 12:01:53,898 INFO App URL: tcp://localhost:60811
2025-02-08 12:01:53,898 INFO Starting Flet View app...
2025-02-08 12:01:53,898 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:01:54,070 INFO App session started
2025-02-08 12:02:12,167 ERROR Future exception was never retrieved
future: <Future finished exception=IntegrityError('UNIQUE constraint failed: items.item_id')>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 247, in on_register_new_item
    add_item_to_db(new_shop_id, new_item_id, new_item_name)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 30, in add_item_to_db
    cursor.execute('''
sqlite3.IntegrityError: UNIQUE constraint failed: items.item_id
2025-02-08 12:02:18,743 ERROR Future exception was never retrieved
future: <Future finished exception=OperationalError('database is locked')>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 247, in on_register_new_item
    add_item_to_db(new_shop_id, new_item_id, new_item_name)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 30, in add_item_to_db
    cursor.execute('''
sqlite3.OperationalError: database is locked
2025-02-08 12:02:19,163 ERROR Future exception was never retrieved
future: <Future finished exception=OperationalError('database is locked')>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 247, in on_register_new_item
    add_item_to_db(new_shop_id, new_item_id, new_item_name)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 30, in add_item_to_db
    cursor.execute('''
sqlite3.OperationalError: database is locked
2025-02-08 12:02:19,334 ERROR Future exception was never retrieved
future: <Future finished exception=OperationalError('database is locked')>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 247, in on_register_new_item
    add_item_to_db(new_shop_id, new_item_id, new_item_name)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 30, in add_item_to_db
    cursor.execute('''
sqlite3.OperationalError: database is locked
2025-02-08 12:02:19,583 ERROR Future exception was never retrieved
future: <Future finished exception=OperationalError('database is locked')>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 247, in on_register_new_item
    add_item_to_db(new_shop_id, new_item_id, new_item_name)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 30, in add_item_to_db
    cursor.execute('''
sqlite3.OperationalError: database is locked
2025-02-08 12:29:19,710 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:29:19,710 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:29:19,710 INFO Starting up TCP server on localhost:60876
2025-02-08 12:29:19,728 INFO Flet app has started...
2025-02-08 12:29:19,728 INFO App URL: tcp://localhost:60876
2025-02-08 12:29:19,728 INFO Starting Flet View app...
2025-02-08 12:29:19,729 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:29:19,893 INFO App session started
2025-02-08 12:32:08,255 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:32:08,256 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:32:08,256 INFO Starting up TCP server on localhost:60893
2025-02-08 12:32:08,260 INFO Flet app has started...
2025-02-08 12:32:08,260 INFO App URL: tcp://localhost:60893
2025-02-08 12:32:08,260 INFO Starting Flet View app...
2025-02-08 12:32:08,261 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:32:08,426 INFO App session started
2025-02-08 12:32:11,853 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:32:12,906 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:32:13,233 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:32:13,394 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:32:13,561 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:32:50,682 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:32:50,683 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:32:50,683 INFO Starting up TCP server on localhost:60900
2025-02-08 12:32:50,687 INFO Flet app has started...
2025-02-08 12:32:50,687 INFO App URL: tcp://localhost:60900
2025-02-08 12:32:50,687 INFO Starting Flet View app...
2025-02-08 12:32:50,688 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:32:50,850 INFO App session started
2025-02-08 12:33:01,341 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:33:01,788 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:33:01,930 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:33:02,067 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:33:02,211 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:33:02,380 ERROR Future exception was never retrieved
future: <Future finished exception=TypeError("delete_item_from_db() missing 1 required positional argument: 'item_id'")>
Traceback (most recent call last):
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 941, in wrapper
    handler(*args)
  File "c:\Users\K.T\Documents\Github\R_ScrapingRank\main.py", line 190, in on_delete_item
    delete_item_from_db(selected_item_id)
TypeError: delete_item_from_db() missing 1 required positional argument: 'item_id'
2025-02-08 12:34:25,501 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:34:25,508 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:34:25,508 INFO Starting up TCP server on localhost:60912
2025-02-08 12:34:25,508 INFO Flet app has started...
2025-02-08 12:34:25,508 INFO App URL: tcp://localhost:60912
2025-02-08 12:34:25,508 INFO Starting Flet View app...
2025-02-08 12:34:25,508 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:34:25,676 INFO App session started
2025-02-08 12:48:49,914 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:48:49,915 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:48:49,916 INFO Starting up TCP server on localhost:60985
2025-02-08 12:48:49,919 INFO Flet app has started...
2025-02-08 12:48:49,919 INFO App URL: tcp://localhost:60985
2025-02-08 12:48:49,919 INFO Starting Flet View app...
2025-02-08 12:48:49,920 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:48:50,277 INFO App session started
2025-02-08 12:50:29,994 INFO Logger is configured with simple rotating file handler.
2025-02-08 12:50:29,994 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 12:50:29,994 INFO Starting up TCP server on localhost:61003
2025-02-08 12:50:29,994 INFO Flet app has started...
2025-02-08 12:50:29,994 INFO App URL: tcp://localhost:61003
2025-02-08 12:50:29,994 INFO Starting Flet View app...
2025-02-08 12:50:29,994 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 12:50:30,166 INFO App session started
2025-02-08 15:51:27,306 INFO Logger is configured with simple rotating file handler.
2025-02-08 15:51:27,306 INFO Assets path configured: C:\Users\K.T\Documents\Github\R_ScrapingRank\assets
2025-02-08 15:51:27,306 INFO Starting up TCP server on localhost:61105
2025-02-08 15:51:27,322 INFO Flet app has started...
2025-02-08 15:51:27,322 INFO App URL: tcp://localhost:61105
2025-02-08 15:51:27,322 INFO Starting Flet View app...
2025-02-08 15:51:27,322 INFO Flet View found in: C:\Users\K.T\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\bin\flet\flet.exe
2025-02-08 15:51:27,709 INFO App session started
